
-- Basic schema for demo
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS drives;
DROP TABLE IF EXISTS companies;

CREATE TABLE students (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  status TEXT CHECK(status IN ('placed','in_process','not_applied')) NOT NULL
);

CREATE TABLE drives (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE companies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company TEXT NOT NULL UNIQUE,
  offers INTEGER NOT NULL DEFAULT 0
);

-- Seed students so that the pie is 45/30/25
-- Total = 100 students
INSERT INTO students(name, status)
SELECT 'Student ' || printf('%02d', n), 'placed' FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45);

INSERT INTO students(name, status)
SELECT 'Student ' || printf('%02d', 45+n), 'in_process' FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30);

INSERT INTO students(name, status)
SELECT 'Student ' || printf('%02d', 75+n), 'not_applied' FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25);

-- Seed drives (0 active to match screenshot)
INSERT INTO drives(company, is_active) VALUES ('TCS', 0);
INSERT INTO drives(company, is_active) VALUES ('Infosys', 0);

-- Company-wise offers (bars ~ 16, 12, 10, 8)
INSERT INTO companies(company, offers) VALUES ('TCS', 16);
INSERT INTO companies(company, offers) VALUES ('Infosys', 12);
INSERT INTO companies(company, offers) VALUES ('Wipro', 10);
INSERT INTO companies(company, offers) VALUES ('Cognizant', 8);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'student'  -- student | admin | recruiter
);
DROP TABLE IF EXISTS drives;
CREATE TABLE drives (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company TEXT NOT NULL,
  title TEXT NOT NULL,            -- e.g., "SDE Intern"
  location TEXT NOT NULL,         -- e.g., "Hyderabad"
  ctc TEXT NOT NULL,              -- e.g., "6–8 LPA"
  deadline TEXT NOT NULL,         -- ISO date as text for demo
  is_active INTEGER NOT NULL DEFAULT 1
);

DROP TABLE IF EXISTS applications;
CREATE TABLE applications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  drive_id INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'applied',  -- applied | shortlisted | interview | offered | rejected | withdrawn
  applied_at TEXT NOT NULL,                -- ISO timestamp
  UNIQUE(user_id, drive_id),
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(drive_id) REFERENCES drives(id)
);


